### ISSUE TITLE
compiling with gcc 5.1 on linux 16 core

### ISSUE THREAD

**Issue by jjoshua2** [syzygy1/Cfish#5]
This is 2x8 system, I believe numa, so I don't know if that affects this? I had an error with GCC 4.8 missing a .h file which was GCCs fault, so I tried GCC 5.1 and got this error. I was able to compile fine on my windows box with 5.3 and 5.4, does it need a recent GCC just to compile?

gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m64 -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DNUMA    -c -o benchmark.o benchmark.c
In file included from benchmark.c:32:0:
tt.h:101:23: error: expected declaration specifiers or ‘...’ before numeric constant
 #define CacheLineSize 64
                       ^
tt.h:111:15: note: in expansion of macro ‘CacheLineSize’
 static_assert(CacheLineSize % sizeof(Cluster) == 0, "Cluster size incorrect");
               ^
tt.h:111:53: error: expected declaration specifiers or ‘...’ before string constant
 static_assert(CacheLineSize % sizeof(Cluster) == 0, "Cluster size incorrect");
                                                     ^
make[2]: *** [benchmark.o] Error 1

**Comment by jjoshua2** [comment]
Your new patch fixed my MADVISE issue where I had to comment out the huge pages. However, it did not fix this part. But, I found that if I comment out the static_assert, it compiles and appears to work fine. Maybe static_assert is not supported on old kernels too?

**Comment by syzygy1** [comment]
Aha is that it. Strange that you got an error at line 101, though.
I'm pretty sure gcc-5.1 supports static_assert, but your assert.h probably does not define it.
I have removed the line.

**Comment by jjoshua2** [comment]
You could just do a check for support like this:
https://stackoverflow.com/questions/25552852/how-to-detect-if-a-compiler-supports-static-assert

**Comment by syzygy1** [comment]
assert.h is included via misc.h, so that's not the problem.
Anyway, that line is only a compile-time check that can easily be missed.
Does Cfish now compiler for you?

**Comment by jjoshua2** [comment]
Yes it compiles fine now. Thanks. I guess you can close this issue.
One request I can make a new issues for.  Can the make file allow a built
in tb path? So I don't have to edit the ucioption

**Comment by syzygy1** [comment]
I was thinking of reading out environment values to initialise the default values of some of the UCI options, which would do what you want.

**Comment by jjoshua2** [comment]
It appears I do use hugepages, just not mdavise, this command shows kernel support
grep HUGETLB /boot/config-$(uname -r)
CONFIG_HUGETLBFS=y
CONFIG_HUGETLB_PAGE=y

This command shows that it is enabled transparently (always is selected), without using madvise
 cat /sys/kernel/mm/redhat_transparent_hugepage/enabled
[always] madvise never

**Comment by syzygy1** [comment]
So hugepages will be used even without the setting in Cfish.
